### ISSUE TITLE
[Proposal] Kordis high-level operations architecture

### ISSUE THREAD

**Issue by timonmasberg** [kordis-leitstelle/kordis#34]
This proposal aims to show a potential hosting variant of Kordis with all it's first- and third-party services.

### Conditions

- 3.5k$ yearly Microsoft Azure credits waiting to get spent :)
- On-prem server is available for usage
- No further expenses
- 3-Tier Architecture 
- Complete self-hosting must be possible without heavy refactoring

### Outcome

Since we “only” have 3.5k$ we want to spend them as wisely as possible. We aim to ensure that the _core platform_ of Kordis is running smoothly and is as resilient as possible. A deployment on-premise (current state) is, from my perspective, not a valid path we should continue to go. With the rising complexity of the application, we should leverage all the automation in our DevOps process we can get. 

**Azure Static Web Apps** allows us to deploy an instance of our Frontend for production and for each change request. It handles certificates and with SLA it costs around $9/mo with 100gb bandwidth (which should be more than enough).
**Azure Web App Services** is a fully managed environment for server-side applications. P2v3 with 4 cores and 16 GB ram costs around $260/mo. Furthermore, App Services offer “slots” which somehow are equal to “stages” but are rather static instead of dynamically created for each change request. Therefore, we have to further investigate how we can deploy our platform _per-change_ . Since we will have at least 2 running instances, P2v3 seems reasonable and is still coverable by the number of credits we get.
**Azure AD B2C** is the active directory variant for non Microsoft accounts that we could use as Identity Provider.
This should be further discussed, as AD is relatively heavy in comparison with services such as Auth0 or Ory.  We also have to pay for each MAU (3ct, can be neglected).
**Azure Cosmos DB** is a serverless database that has an adapter for MongoDB and a very generous free plan (25 GB and 1000 Request Units) with 7-day backups. As we are already in the Azure ecosystem, wanted to use a NoSQL-DB, preferably MongoDB which also is “easily” self-hostable, and we are not likely to hit the free-limits, we should just use it.

For everything we consider “non-core” and that requires higher resources that we couldn't cover with our credits, we should use our on-premise server.

![kordis high level landscape drawio](https://user-images.githubusercontent.com/13659466/215887708-a5080169-b143-46c2-bec2-d5f21be9ac85.png)

**[1]:** Frontend being served with Azure SWA.
**[2]:** User-Auth Flow managed by Azure AD.
**[3]:** Backend.
**[4]:** Auth Management.
**[5]:** Frontend connects to MapTiler for Vector Maps and Cartesius for Geocoding Services.
**[6]:** Backend connects to Database and further services such as Azure Maps and Cartesius.
**[7]:** Connection to our on-prem system. We need to discuss how we’ll handle authentication. We could also integrate the system into our Azure ecosystem with a VPN and treat them as internal services.
**[8]:** On-prem system connects and wraps resource hungry services such as AIS from HPA.

**Comment by JSPRH** [comment]
Results of our weekly on 05/02/23:
* We will avoid running anything on-prem as much as possible. This is because the discussion revealed
  1. Communication between on-prem services and the backend in Azure would add a lot of complexity we want to avoid
  2. The computing power our backend has (4 cores, 16G ram) is probably quite sufficient to run multiple stages of the backend including services we initially intended to run on-prem
  3. The data throughput coming in from external data sources like HPA will be in the double-digit Mbit/s. So having it in the cloud will reduce the load on our on-prem infrastructure.
  4. We can probably cache data from external data sources in-memory instead of needing a dedicated database
* Instead of the DWD API, we intend to use the [NINA API](https://nina.api.bund.dev/) since we have to fetch fewer data
* The current IDP solution Azure AD is tbd since feature-scope and usability are unclear yet. Our goal with the IDP selection is to keep it as simple as possible while avoiding vendor lock-in. Alternatives would be [Ory](https://www.ory.sh/identity-authentication/) or [Auth0](https://auth0.com/de/access-management).

> we should leverage all the automation in our DevOps process we can get.

Using on-prem is less about automation than it is about added complexity and work. However, generally, I agree that we should avoid adding complexity and reduce work where possible.

**Comment by timonmasberg** [comment]
![kordis high level landscape drawio (1)](https://user-images.githubusercontent.com/13659466/226492268-6a0bfe73-2201-4441-a9d7-f654e9fa6ab6.png)

[1]: Frontend _SPA_ being served with Azure SWA.
[2]: User-Auth Flow managed by Azure AD.
[3]: Backend _API_ being served with Azure Web Apps (App Services.
[4]: Token Storage/ User Management
[5]: Frontend connects to MapTiler for Vector Maps and Cartesius for Geocoding Services.
[6]: Backend connects to Database and further services such as Azure Maps and Cartesius.
[7]: Backend also to 3rd Party Services such as the [NINA API](https://nina.api.bund.dev/).

@JSPRH is this something we want to put in an ADR or maybe a dedicated doc file?

**Comment by timonmasberg** [comment]
Weekly decision: Should be in a dedicated file under /docs
